const data = [
  {
    newsId: `01LNRNg7du4PkHXCWltm`,
    title: `Elon Musk tweeted to create an ‘everything app’; what is it?`,
    description: `Musk is now willing to proceed with his original plan to buy the social media company for $44 billion and late on Tuesday he tweeted: “Buying Twitter is an accelerant to creating X, the everything app.” The concept of an everything app, often referred to as a “super app,” is massively popular in Asia and tech companies across the world have tried to replicate it. A super app, or what Musk refers to as an “everything app,” has been described as the Swiss army knife of mobile apps, offering a suite of services for users such as messaging, social networking, peer-to-peer payments and e-commerce shopping.`,
    creationDate: Date.now() - 14400000,
    readTime: 120,
  },
  {
    newsId: `07bkspz4kVlG4X3Oph6l`,
    title: `This Diwali, Flipkart to woo customers with a Metaverse shopping experience`,
    description: `Flipkart﻿ is launching Flipverse, an interactive virtual shopping destination, in India. Sources close to the development have confirmed to The Decrypting Story that the ecommerce giant has teamed up with social media behemoth Meta and Ethereum scaling solution Polygon for the project. Social media influencer Mukul Sharma tweeted about Flipverse's launch. The source said that Flipkart is expected to make an official announcement of Flipverse during Flipkart's Big Billion Day sale, which takes place during Diwali.`,
    creationDate: Date.now() - 86400000 * 2,
    readTime: 180,
  },
  {
    newsId: `0D3H6WobHV0AJPO00Kti`,
    title: `Chinese vlogger gets into trouble, after eating a great white shark`,
    description: `Influencer from china is under police investigation after a clip of her roasting and eating a great white shark went viral. Tiji (vlogger name) said, 'It may look vicious, but its meat is truly very tender,' while tearing off large chunks of the animal's barbecued meat, in a video posted in mid-July. In China, they great white shark listed as protected. Illegal possession can lead to a five-to-10-year prison term.`,
    creationDate: Date.now() - 86400000 * 3,
    readTime: 240,
  },
  {
    newsId: `0Ekr2pLriNZzs31Uvp7M`,
    title: `Virat Kohli and Priyanka Chopra rank first and second in Asian influencers`,
    description: `India’s very own Virat Kohli, the former Indian cricket team captain, is ranked as the first-highest-earning celebrity on Instagram and the third-highest-earning celebrity with an estimated earning of $36.7 million purely through Instagram sponsorships. The only Bollywood actress, global icon and most talked Indian celebrity Priyanka Chopra Jonas endorses multiple brands like Bumble, Appy Fizz, Schmitten Luxury Chocolates and so on. Her earning per Instagram post is $423k and she is the second Asian Indian influencer with the highest earnings per Instagram post.`,
    creationDate: Date.now() - 86400000 * 4,
    readTime: 120,
  },
  {
    newsId: `0FHoU6WYbeU3dZE2COCs`,
    title: `Lionel Messi is BYJU'S ambassador of 'Education for All'`,
    description: `Ed-tech firm BYJU'S on Friday announced football star and global sports icon Lionel Messi as the global brand ambassador of its social impact arm -- Education For All. Lionel Messi, who plays for Paris Saint-Germain and captains the Argentinian football team, has signed an agreement with BYJU'S to promote the cause of equitable education. This association with one of the world's most popular sports persons is in sync with the expanding global footprint of BYJU'S and its commitment to making education accessible, equitable, and affordable for all, a statement said on Friday.`,
    creationDate: Date.now() - 86400000 * 6,
    readTime: 180,
  },
  {
    newsId: `0SSaZ9Zb7SbqhM0gvM6s`,
    title: `Logan Paul Will Take On Roman Reigns For The WWE Championship Title`,
    description: `Logan Paul will fight Undisputed WWE Universal Championship holder Roman Reigns at Crown Jewel, set to take place on November 5 in Riyadh, Saudi Arabia. The announcement was made last night by Triple H at the WWE press event held in Las Vegas.n"We need to talk about Crown Jewel, and we need to talk about the biggest spectacle that will be happening on November 5 in Saudi Arabia," said Triple H.`,
    creationDate: Date.now() - 86400000 * 7,
    readTime: 240,
  },
  {
    newsId: `0TrfHSKxhRUM3GftFmOC`,
    title: `TheSaudis NFTs : Latest collection gets Twitter personalities fueled up`,
    description: `"TheSaudis" NFT topped the volume charts in its debut weekend with $7.7 million in sales. The collection of 5,555 NFTs, whose artwork is a derivative of the famed CryptoPunks collectables, was free to mint on July 9 & sold out within hours. The project kept its momentum going with goblin noise-filled Twitter Spaces and influencer partnerships, most recently taking over NFT.NYC with a slew of ghoul-themed parties. Many of whom created Saudi Arabia-inspired meme videos to fuel the project’s hype.`,
    creationDate: Date.now() - 86400000 * 9,
    readTime: 120,
  },
  {
    newsId: `0UAVlJhd3cpXyrQfwKrO`,
    title: `Bira 91 partners with Warner Bros. Consumer Products for House of the Dragon merchandise`,
    description: `Bira 91, in collaboration with Warner Bros. Consumer Products, has announced the launch of an exclusive merchandise collection inspired by the newly released HBO Original series House of the Dragon, the successor series to Game of Thrones. The exclusive House of the Dragon x Bira 91 merchandise celebrates the season of Fire and Blood and is dedicated to fans across India. The collection includes products inspired by the Seven Kingdoms and is perfect for fans to display their love for the world of Targaryens.`,
    creationDate: Date.now() - 86400000 * 10,
    readTime: 180,
  },
  {
    newsId: `0kQrxBak2CqhspJXqmsc`,
    title: `ESPN launches creator network to attract Gen Z`,
    description: `ESPN is launching ESPN Creator Network, providing up-and-coming content creators with access to ESPN’s sports properties and resources. The first iteration will feature 10 creators and focus on TikTok. It will begin in October and run for about four months. The creator network is a partnership with social-led content agency Blue Hour Studios. The ESPN Creator Network follows similar efforts by other publishers and social platforms that are seeking to engage with Gen Z by boosting support for content creators.`,
    creationDate: Date.now() - 86400000 * 12,
    readTime: 240,
  },
  {
    newsId: `0kuQo3CAFP6IOeKhQsuA`,
    title: `Companies Using Influencers to Hire People`,
    description: `Companies across the country continue to struggle to find workers to fill vacancies. Labor shortages themselves are a complex issue with many  factors, but today's brands have  surprisingly effective contacts when it comes to hiring. Whether the goal is to raise awareness, sell products, or hire the right employees, influencer marketing can open the door to genuine brand engagement with results.`,
    creationDate: Date.now() - 86400000 * 13,
    readTime: 120,
  },
  {
    newsId: `0lvEWzfNufPxYQLBWbvS`,
    title: `Social media influencer booked for cheating doctor of Rs 4.5 crore with medical college promise`,
    description: `A social media influencer has been booked for allegedly duping a homeopath of Rs 4.5 crore by promising to get a medical college sanctioned in his name and "saving him from arrest" in a non-existent Central Bureau of Investigation case, Nagpur police said on Thursday. The victim came in contact with the accused through a relative and spoke of his desire to start a homeopathy college, the Kotwali police station official said. "The accused extorted Rs 4.5 crore from the victim by claiming he had contacts with various departments in the Union and state governments. He also took money from the victim after finding out the latter was a guarantor for a bank loan," the official said.`,
    creationDate: Date.now() - 86400000 * 15,
    readTime: 180,
  },
  {
    newsId: `0v7yhLdLjS48dE0IHA6M`,
    title: `South Korea 'cryptocrash' boss faces arrest warrant`,
    description: `A spokesperson for the South Korean prosecutor's office told the BBC that arrest warrants had been issued for Kwon and five other individuals connected to the case. However, she declined to comment on how close authorities were to making the arrests.According to media reports Mr Kwon is believed to be in Singapore, which does not have an extradition agreement with South Korea.`,
    creationDate: Date.now() - 86400000 * 17,
    readTime: 240,
  },
  {
    newsId: `0w7sR87oceuFpXkpzMxH`,
    title: `VR headset that can actually kill you if you die in-game :Oculus Founder`,
    description: `In a blog post, Palmer Luckey the founder VR headset oculus said he was inspired by the Japanese novel series-turned-anime 'Sword Art Online'. In it, players are entrapped in an online role-playing game where death in the game implies death in the real world due to the lethal "NerveGear" headset they wear. “The idea of tying your real life to your virtual avatar has always fascinated me - you instantly raise the stakes to the maximum level and force people to fundamentally rethink how they interact with the virtual world and the players inside it,” Luckey said.`,
    creationDate: Date.now() - 86400000 * 18,
    readTime: 120,
  },
  {
    newsId: `0x5ecxioR5Y7laED9zyQ`,
    title: `Valorant Harbor Celebrated in Indian Culture with famous Gamerz`,
    description: `The launch party for Harbor saw the participation of famous Indian celebrities including Tanmay Bhat and Abish Mathew. They were joined by Ocean Sharma and a number of well-known Indian influencers, including Ujjwal Chaurasia (Techno Gamerz), Naman Mathur (MortaL), Tanmay Singh (Scout) and Shagufta Iqbal (Xyaa). Valorant pro players including Ganesh “SkRossi” Gangadhar, Rishab “Rakazone” Karanwal, Rohan “HydraFlick” Ledwani, and Sabyasachi "Antidote" Bose were also among those present. The event concluded with a performance from ARB4, Mangal Suvarnan, and Tienas, the music team that produced Harbor’s theme song, RAJA.`,
    creationDate: Date.now() - 86400000 * 20,
    readTime: 180,
  },
  {
    newsId: `0z1Q1Z2fF3Ghwi0427tS`,
    title: `Twitter is down, many users facing issues in accessing the social media site`,
    description: `Twitter was down this morning, making it difficult for many users to access their accounts. Since they are unable to view anything on the microblogging page, users are having problems accessing their Twitter feed. When the feed page initially loads, a popup with the message "Something Went Wrong, But Don't Worry - Try Again" displays. Users of apps appear to be able to access their feed but Web users are unable to do so.`,
    creationDate: Date.now() - 86400000 * 21,
    readTime: 240,
  },
  {
    newsId: `14BVrSWBCoijc3peinjY`,
    title: `Jasmin Bhasin’s Prettiest Looks In Pink Will Give You Sleepless Nights`,
    description: `The diva has proven her strength through both her acting prowess and her sense of style. Due to her glamorous online persona, the actor has a big fan base and is highly active on social media. Jasmin Bhasin appears to be a big fan of pink outfits according to her social media accounts. She frequently dresses in pink for photo sessions. Jasmin is stunning in every outfit, whether it is western or traditional.`,
    creationDate: Date.now() - 86400000 * 23,
    readTime: 120,
  },
  {
    newsId: `if8mf9iped4vet2czb14`,
    title: `U.S. mulling a probe of deceptive advertising on social media`,
    description: `The U.S. Federal Trade Commission is expected to vote next week on whether to send demands for information about deceptive advertising to eight social media and video streaming companies, the agency said on Thursday. The agency did not say which social media companies would receive the demands but said that the information would be used to determine what steps they have taken to detect and remove deceptive advertising from their platforms. Some of the biggest social media companies are Facebook (NASDAQ: META) and its subsidiaries Instagram and WhatsApp. Top video streaming platforms include Alphabet (NASDAQ: GOOGL)'s YouTube and TikTok.`,
    creationDate: Date.now() - 86400000 * 25,
    readTime: 180,
  },
  {
    newsId: `mec8ljyduzw46gvw3a6q`,
    title: `Second-biggest bank collapse in U.S. history happened in just 48 hours`,
    description: `On Wednesday, Silicon Valley Bank was a well-capitalized institution seeking to raise some funds. Within 48 hours, a panic induced by the very venture capital community that SVB had served and nurtured ended the bank’s 40-year run. Regulators shuttered SVB Friday and seized its deposits in the largest U.S. banking failure since the 2008 financial crisis and the second-largest ever. The company’s downward spiral began late Wednesday when it surprised investors with news that it needed to raise $2.25 billion to shore up its balance sheet. What followed was the rapid collapse of a highly-respected bank that had grown alongside its technology clients. The episode is the latest fallout from the Federal Reserve’s actions to stem inflation with its most aggressive rate-hiking campaign in four decades.`,
    creationDate: Date.now() - 86400000 * 26,
    readTime: 240,
  },
  {
    newsId: `1es52ugmnmpfaf098jmo`,
    title: `Key US Intelligence Official Casts Shade on TikTok, Chinese Tech`,
    description: `Add a top U.S. intelligence official to the list of Americans expressing concern about Chinese-made technology and Chinese social media platforms like TikTok. General Paul Nakasone, who heads both the U.S. Cyber Command and the National Security Agency, told lawmakers Tuesday there are multiple reasons to be wary of China’s rapid expansion in cyberspace, calling Beijing "a very formidable foe." "TikTok concerns me for a number of different reasons," Nakasone said during a Senate Armed Services Committee hearing. "One is the data that they have. Secondly are the algorithm and the control. Who has the algorithm?" Third, he said, "is the broad platform" both for unleashing potential influence operations but also for the ability to give China a way to "turn off the message."
    `,
    creationDate: Date.now() - 86400000 * 28,
    readTime: 120,
  },
  {
    newsId: `iza5uhjxhku1fpg6p54n`,
    title: `Meta to Build Standalone Social Media to Compete With Twitter`,
    description: `According to Platformer, a tech newsletter, the project is codenamed P92 and would be built as a separate app, but users would use Instagram details to log in. The move, CNBC reported, is to help Meta attract some of Twitter's dissatisfied users looking for alternative platforms after Musk took over the site. "We're exploring a standalone decentralized social network for sharing text updates. "We believe there's an opportunity for a separate space where creators and public figures can share timely updates about their interests." The project would increase Meta's offerings beyond Facebook, WhatsApp, and Instagram and launch it into a Twitter-dominated ecosystem. Instagram head Adam Mosseri reportedly leads the project.
    `,
    creationDate: Date.now() - 86400000 * 30,
    readTime: 180,
  },
  {
    newsId: `andgygojwuap60y6is7y`,
    title: `TikTok Bans Inch Closer in the US and EU`,
    description: `With the pressure rising on TikTok, as it faces potential bans in the US and Europe due to concerns around its exposure to the CCP, the company has launched new efforts to win over policymakers in both regions, in the hopes of avoiding further restrictions, and losing billions in future revenue. The concerted efforts highlight just how serious the situation has become for the company, which is also facing possible restrictions in Canada and Australia as well. And really, if one region shuts it down, it seems increasingly likely that others will follow, which could be a virtual death blow for the app.`,
    creationDate: Date.now() - 86400000 * 31,
    readTime: 120,
  },
  {
    newsId: `5lh23q47d6syyx0hlqbk`,
    title: `Danish public broadcaster advises staff against using TikTok`,
    description: `Denmark's public-service broadcaster has advised staff not to have TikTok on their work phones, because of security concerns. DR said the decision followed a security review and warnings from Denmark's Centre for Cyber Security. Journalists needing access to the app for research must now ask for permission to use what staff is calling special "TikTok phones". DR is the first news organization to issue such advice. TikTok is run from Singapore but its parent company, ByteDance, is based in Beijing, leading to growing fears, in Europe and the United States, the Chinese government could compel it to spy on users or hand over their data. TikTok and ByteDance have always denied those accusations.`,
    creationDate: Date.now() - 86400000 * 33,
    readTime: 180,
  },
  {
    newsId: `kvxzublg5tu9sv53r0ii`,
    title: `Instagram apologizes after thousands of users in Australia and overseas report outages on the app`,
    description: `Instagram has issued an apology after thousands of users in Australia and around the world reported an outage on the social media giant's app. In a statement posted on Twitter just after 4 pm, Instagram said the bug had been resolved. "Earlier (today), a technical issue caused people to have trouble accessing Instagram," it said. "We resolved this issue for everyone as quickly as possible, and we apologize for any inconvenience.﻿" Outage tracking website DownDetector showed ﻿two spikes of global users experiencing issues with a social media platform, one of 57,398 reports just before 1 pm and the other an hour later with 52,143. Australian outages tracked by the site peaked at 2476 at 1.55 pm.`,
    creationDate: Date.now() - 86400000 * 35,
    readTime: 120,
  },
  {
    newsId: `17fzcyfr9rzv7wc08c9h`,
    title: `Alvie is Australia’s first social app for people with disabilities`,
    description: `For many people living with disability, connecting through apps with others who share similar life experiences can be challenging. Most mainstream social networking sites have blind spots when it comes to the safety, accessibility, inclusivity, and support needs of people with disabilities. That’s why disabilities community organizer Steve Bear created Alvie, the country’s first social platform uniquely designed for people who live with disabilities. The app aims to connect those living with disabilities with like-minded people who share similar life experiences, interests, and hobbies, facilitating relationships and enriching friendships. For Bear, the app’s central purpose is providing emotional assistance — especially from loneliness.`,
    creationDate: Date.now() - 86400000 * 37,
    readTime: 180,
  },
  {
    newsId: `t389gwtde15joh300z2s`,
    title: `TikTok, Twitter, and Facebook are set to face an EU crackdown on toxic content`,
    description: `The largest tech platforms will have to adhere to requirements to limit disinformation and better protect children online. TikTok, Twitter, Facebook, and Instagram have now confirmed they will face the strictest rules under the EU’s content-moderation law, the Digital Services Act (DSA). Online platforms have until Friday at midnight to reveal how many Europeans use their services under the DSA. Platforms and search engines with over 45 million EU users will have to adhere to sweeping requirements starting in the summer of 2023 including swiftly taking down illegal content, limiting disinformation, and better protecting kids and teenagers under the supervision of the European Commission. TikTok said on Friday in a blog post it had counted an average of 125 million monthly active users in the bloc between August 2022 and January 2023.`,
    creationDate: Date.now() - 86400000 * 38,
    readTime: 120,
  },
  {
    newsId: `x2dwv6z1vdxih4wa4x7e`,
    title: `72% of internet users in the European Union now get their news online`,
    description: `New figures from the European Union’s statistical office Eurostat confirm that the consumption of news online is continuing to grow. The data from 2021 shows that 72% of internet users aged 16-74 in the EU read news sites, newspapers, and news magazines online. That’s a 2 percentage point increase compared with 2016. Breaking it down by countries, the highest percentages of people reading news online were found in Finland (93%), Lithuania and the Czech Republic (both 92%), and Croatia and Greece (both 90%). Romania reported the lowest usage (59%), closely followed by Germany (62%), France (63%), Italy (64%), and Belgium (67%).`,
    creationDate: Date.now() - 86400000 * 40,
    readTime: 180,
  },
];

export default data;
